# Generated by Django 5.0.4 on 2024-04-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_carttenancy"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="image",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name="CartTenancy",
        ),
    ]
