# Generated by Django 5.0.4 on 2024-05-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_orderitem_image_delete_carttenancy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="/placeholder.png", null=True, upload_to=""
            ),
        ),
    ]
